
language: node_js
sudo: false
git:
  depth: 1
cache:
  directories:
    - $HOME/.npm
    - node_modules
matrix:
  include:
    - node_js: "11"
      script: npm test
      env: CI=test 11
    - node_js: "12"
      script: npm test
      env: CI=test 12
    - node_js: "12"
      script: npm test -- --runInBand --coverage
      env: CI=coverage
    - node_js: "13"
      script: npm test
      env: CI=test 13
before_install:
  - npm install -g npm@latest
after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls; fi